[package]
name = "coup"
version = "0.1.0"
authors = ["Brendon Daugherty <brendond@fb.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.25"
log = "0.4.8"
rand = "0.7.3"
enumset = "0.4.5"

